function StandardQuiz({ mode, onBack, settings, wordDatabase, qualifyingBook, onSaveScore }) {
    const [queue, setQueue] = useState([]);
    const [currentQuestion, setCurrentQuestion] = useState(null);
    const [inputVal, setInputVal] = useState('');
    const [feedback, setFeedback] = useState(null);
    const [isFinished, setIsFinished] = useState(false);
    const [hasStarted, setHasStarted] = useState(false); 
    const [stats, setStats] = useState({ correct: 0, wrong: 0 });
    const inputRef = useRef(null);
    const [startTime, setStartTime] = useState(null);
    const [elapsedTime, setElapsedTime] = useState(0);
    const [playerName, setPlayerName] = useState('');
    const [nameError, setNameError] = useState('');
    const [scoreSaved, setScoreSaved] = useState(false);

    useEffect(() => { let filtered = wordDatabase.filter(w => settings.selectedUnits.includes(`${w.book}-${w.lesson}`)); let shuffled = [...filtered].sort(() => 0.5 - Math.random()); if (settings.count !== 'all') shuffled = shuffled.slice(0, parseInt(settings.count, 10)); setQueue(shuffled); setCurrentQuestion(shuffled[0]); }, [settings, wordDatabase, mode]);
    useEffect(() => { if (hasStarted && mode === 'listening' && currentQuestion && !isFinished) setTimeout(() => playAudio(currentQuestion.en), 300); }, [currentQuestion, hasStarted, mode, isFinished]);
    const handleStart = () => { if (queue.length === 0) { alert("此範圍無題目！"); return onBack(); } if ('speechSynthesis' in window) window.speechSynthesis.cancel(); setHasStarted(true); setStartTime(Date.now()); };
    const handleSubmit = (e) => { e?.preventDefault(); if (!inputVal.trim() || feedback) return; let isCorrect = false; const ans = inputVal.trim().toLowerCase(); if (mode === 'zh-en' || mode === 'listening' || mode === 'hard') isCorrect = (ans === currentQuestion.en.toLowerCase()); else if (mode === 'en-zh') isCorrect = ans.split(/[、,，/]/).map(w=>w.trim()).some(u => currentQuestion.zh.split(/[、,，/]/).map(w=>w.trim()).includes(u)); if (isCorrect) { setFeedback('correct'); setStats(s => ({ ...s, correct: s.correct + 1 })); soundEngine.correct(); setTimeout(() => moveToNext(true), 1000); } else { setFeedback('incorrect'); setStats(s => ({ ...s, wrong: s.wrong + 1 })); soundEngine.wrong(); setTimeout(() => moveToNext(false), 2000); } };
    const moveToNext = (wasCorrect) => { setFeedback(null); setInputVal(''); inputRef.current?.focus(); const newQ = [...queue]; const curr = newQ.shift(); if (!wasCorrect) newQ.push(curr); if (newQ.length > 0) { setQueue(newQ); setCurrentQuestion(newQ[0]); } else { setElapsedTime(Math.floor((Date.now() - startTime) / 1000)); setIsFinished(true); soundEngine.win(); } };
    const submitToLeaderboard = () => { if (!isValidName(playerName)) { setNameError('請輸入正確的姓名格式'); return; } if (containsProfanity(playerName)) { setNameError('請勿使用不雅字眼'); return; } onSaveScore({ book: qualifyingBook, mode: mode, name: playerName.trim(), score: stats.correct, time: elapsedTime, week: getWeekNumber(), timestamp: Date.now() }); setScoreSaved(true); };

    if (!hasStarted) return <div className="flex-1 flex flex-col items-center justify-center p-6"><div className="bg-white rounded-3xl shadow-xl p-10 max-w-md w-full text-center"><button onClick={handleStart} className="w-full py-4 bg-blue-600 text-white rounded-xl font-bold text-lg shadow-lg hover:scale-105">開始測驗</button><button onClick={onBack} className="w-full mt-4 text-slate-500 font-semibold">取消</button></div></div>;
    if (isFinished) return <div className="flex-1 flex flex-col items-center justify-center p-6"><div className="bg-white rounded-3xl shadow-xl p-10 max-w-md w-full text-center relative"><i className="fa-solid fa-trophy text-yellow-400 mb-6 text-6xl"></i><h2 className="text-3xl font-bold mb-2">測驗完成！</h2><p className="mb-6">花費了 <span className="font-bold text-blue-600">{elapsedTime} 秒</span></p><div className="flex justify-center gap-8 mb-8"><div><div className="text-4xl font-black text-emerald-500">{stats.correct}</div><div className="text-sm font-bold text-slate-400 mt-1">答對</div></div><div><div className="text-4xl font-black text-red-400">{stats.wrong}</div><div className="text-sm font-bold text-slate-400 mt-1">重答</div></div></div>{qualifyingBook !== null && !scoreSaved ? (<div className="mt-4 mb-8 p-5 bg-yellow-50 rounded-2xl border border-yellow-300"><input type="text" value={playerName} onChange={e => {setPlayerName(e.target.value); setNameError('');}} placeholder="輸入英雄姓名" className="w-full p-3 rounded-xl border-2 border-yellow-300 text-center mb-2 font-bold" onKeyDown={e => e.key === 'Enter' && submitToLeaderboard()} /><button onClick={submitToLeaderboard} className="w-full py-3 bg-gradient-to-r from-yellow-400 to-amber-500 text-yellow-950 font-black rounded-xl shadow-md">留名榮譽榜</button></div>) : scoreSaved ? (<div className="mb-8 p-4 bg-emerald-50 text-emerald-700 rounded-2xl font-bold border"><i className="fa-solid fa-circle-check"></i> 成績已上傳！</div>) : null}<button onClick={onBack} className="w-full py-4 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl font-bold">返回大廳</button></div></div>;
    return <div className="flex-1 flex flex-col relative w-full"><header className="flex items-center p-4 bg-white shadow-sm z-10 w-full"><button onClick={onBack} className="text-slate-500 hover:text-blue-600"><i className="fa-solid fa-chevron-left"></i> 返回</button><h1 className="flex-1 text-center font-bold text-lg">{mode==='zh-en'?'中翻英':mode==='en-zh'?'英翻中':mode==='listening'?'聽力':'測驗'}</h1><div className="w-16"></div></header><main className="flex-1 flex flex-col items-center justify-center p-4 w-full">{currentQuestion && (<div className="w-full max-w-2xl"><div className="bg-white rounded-3xl shadow-xl overflow-hidden flex flex-col min-h-[400px] border"><div className="flex-1 flex items-center justify-center p-8 bg-gradient-to-br from-blue-50 to-indigo-50 border-b">{mode === 'zh-en' || mode === 'hard' ? <h2 className="text-5xl font-bold text-center">{currentQuestion.zh}</h2> : mode === 'en-zh' ? <h2 className="text-5xl font-bold text-center">{currentQuestion.en}</h2> : mode === 'listening' ? <button onClick={() => playAudio(currentQuestion.en)} className="p-8 bg-blue-100 text-blue-600 rounded-full shadow-sm hover:scale-105"><i className="fa-solid fa-volume-high text-6xl"></i></button> : null}</div><div className="p-8 relative">{feedback && (<div className={`absolute inset-0 z-10 flex flex-col items-center justify-center backdrop-blur-sm ${feedback === 'correct' ? 'bg-emerald-50/90' : 'bg-red-50/90'}`}>{feedback === 'correct' ? <div className="text-emerald-600 font-bold text-3xl text-center"><i className="fa-solid fa-check text-5xl mb-2"></i><br/>答對了！</div> : <div className="text-center"><p className="text-red-600 font-bold text-2xl mb-2">再試一次！</p><p className="text-lg">開牌正確答案：<span className="font-bold text-2xl ml-2 text-red-600 border-b-2 border-red-400">{mode === 'en-zh' ? currentQuestion.zh : currentQuestion.en}</span></p></div>}</div>)}<form onSubmit={handleSubmit} className="flex gap-4"><input ref={inputRef} type="text" value={inputVal} onChange={(e) => setInputVal(e.target.value)} placeholder="請輸入答案..." className="flex-1 text-2xl p-4 bg-slate-100 border-2 focus:border-blue-400 rounded-xl outline-none text-center font-medium" autoFocus disabled={feedback !== null} autoComplete="off" /><button type="submit" disabled={!inputVal.trim() || feedback !== null} className="bg-blue-600 text-white px-8 py-4 rounded-xl font-bold disabled:bg-slate-300"><i className="fa-solid fa-paper-plane text-2xl"></i></button></form></div></div></div>)}</main></div>;
}
