-- ============================================================
-- 完整匯入 8 冊官方題庫 (共 366 個單字)
-- 請在 Supabase 後台「SQL Editor」中貼上並執行「Run」
-- ============================================================

INSERT INTO public.words (author, book, lesson, en, zh, cloze) VALUES
('Official', '2', 'Starter', 'eleven', '十一', ''),
('Official', '2', 'Starter', 'twelve', '十二', ''),
('Official', '2', 'Starter', 'thirteen', '十三', ''),
('Official', '2', 'Starter', 'fourteen', '十四', ''),
('Official', '2', 'Starter', 'fifteen', '十五', ''),
('Official', '2', '1', 'small', '小的', ''),
('Official', '2', '1', 'big', '大的', ''),
('Official', '2', '1', 'dog', '狗', 'It''s a small ___. (dog, eleven, small)'),
('Official', '2', '1', 'cat', '貓', 'Is that a ___? (red, apple, cat)'),
('Official', '2', '1', 'bird', '鳥', 'It''s a blue ___. ( Mia, eleven, bird)'),
('Official', '2', '1', 'fish', '魚', 'Is this a ___? ( fish, five, eraser)'),
('Official', '2', '1', 'no', '不', ''),
('Official', '2', '1', 'not', '不是', 'No, It''s ___. ( yes, not, no)'),
('Official', '2', '1', 'yes', '是', '___, it is. ( Yes, No, Not)'),
('Official', '2', '2', 'dance', '跳舞', 'Can you ___? (small, bird, dance)'),
('Official', '2', '2', 'draw', '畫畫', 'I can ___. (draw, big, pen)'),
('Official', '2', '2', 'jump', '跳', ''),
('Official', '2', '2', 'read', '閱讀', ''),
('Official', '2', '2', 'sing', '唱歌', ''),
('Official', '2', '2', 'swim', '游泳', ''),
('Official', '2', '2', 'write', '寫字', ''),
('Official', '2', '2', 'can', '能、會', ''),
('Official', '2', '2', 'do', '做', ''),
('Official', '2', '3', 'grandfather', '爺爺', ''),
('Official', '2', '3', 'grandmother', '奶奶', ''),
('Official', '2', '3', 'father', '爸爸', ''),
('Official', '2', '3', 'mother', '媽媽', ''),
('Official', '2', '3', 'brother', '哥哥、弟弟', ''),
('Official', '2', '3', 'sister', '姊姊、妹妹', ''),
('Official', '2', '3', 'tall', '高的', ''),
('Official', '2', '3', 'short', '矮的', ''),
('Official', '2', '3', 'who', '誰', ''),
('Official', '2', '3', 'he', '他', ''),
('Official', '2', '3', 'she', '她', ''),
('Official', '2', '4', 'student', '學生', ''),
('Official', '2', '4', 'teacher', '教師', ''),
('Official', '2', '4', 'doctor', '醫生', ''),
('Official', '2', '4', 'nurse', '護士、護理師', ''),
('Official', '2', '4', 'cook', '廚師', ''),
('Official', '2', '4', 'driver', '司機', ''),
('Official', '2', 'Festival', 'card', '卡片', ''),
('Official', '2', 'Festival', 'flower', '花', ''),
('Official', '2', 'Festival', 'gift', '禮物', ''),
('Official', '2', 'Festival', 'heart', '心', ''),
('Official', '2', 'Festival', 'love', '愛', ''),
('Official', '4', 'Starter', 'twenty-one', '二十一', ''),
('Official', '4', 'Starter', 'twenty-two', '二十二', ''),
('Official', '4', 'Starter', 'twenty-three', '二十三', ''),
('Official', '4', 'Starter', 'twenty-four', '二十四', ''),
('Official', '4', 'Starter', 'twenty-five', '二十五', ''),
('Official', '4', 'Starter', 'twenty-six', '二十六', ''),
('Official', '4', 'Starter', 'twenty-seven', '二十七', ''),
('Official', '4', 'Starter', 'twenty-eight', '二十八', ''),
('Official', '4', 'Starter', 'twenty-nine', '二十九', ''),
('Official', '4', 'Starter', 'thirty', '三十', ''),
('Official', '4', '1', 'twenty', '二十', ''),
('Official', '4', '1', 'thirty', '三十', ''),
('Official', '4', '1', 'forty', '四十', ''),
('Official', '4', '1', 'fifty', '五十', ''),
('Official', '4', '1', 'twenty-five', '二十五', ''),
('Official', '4', '1', 'thirty-five', '三十五', ''),
('Official', '4', '1', 'forty-five', '四十五', ''),
('Official', '4', '1', 'fifty-five', '五十五', ''),
('Official', '4', '1', 'time', '時間', ''),
('Official', '4', '2', 'drinking', '正在喝、喝', ''),
('Official', '4', '2', 'eating', '正在吃、吃', ''),
('Official', '4', '2', 'reading', '正在閱讀、閱讀', ''),
('Official', '4', '2', 'sleeping', '正在睡覺、睡覺', ''),
('Official', '4', '2', 'writing', '正在寫字、寫字', ''),
('Official', '4', '2', 'running', '正在跑步、跑步', ''),
('Official', '4', '2', 'swimming', '正在游泳、游泳', ''),
('Official', '4', '2', 'doing', '正在做、做', ''),
('Official', '4', '3', 'bathroom', '浴室', ''),
('Official', '4', '3', 'bedroom', '臥室', ''),
('Official', '4', '3', 'dining room', '飯廳', ''),
('Official', '4', '3', 'living room', '客廳', ''),
('Official', '4', '3', 'kitchen', '廚房', ''),
('Official', '4', '3', 'yard', '院子', ''),
('Official', '4', '3', 'where', '哪裡', ''),
('Official', '4', '4', 'bag', '包包、袋子', ''),
('Official', '4', '4', 'box', '箱子', ''),
('Official', '4', '4', 'chair', '椅子', ''),
('Official', '4', '4', 'computer', '電腦', ''),
('Official', '4', '4', 'desk', '書桌', ''),
('Official', '4', '4', 'table', '桌子', ''),
('Official', '4', '4', 'in', '在...裡面', ''),
('Official', '4', '4', 'on', '在...上面', ''),
('Official', '4', '4', 'under', '在...下面', ''),
('Official', '4', '4', 'by', '在...旁邊', ''),
('Official', '4', 'Festival', 'Easter', '復活節', ''),
('Official', '4', 'Festival', 'bunny', '兔子', ''),
('Official', '4', 'Festival', 'basket', '籃子', ''),
('Official', '4', 'Festival', 'egg hunting', '找彩蛋', ''),
('Official', '6', 'Starter', 'one hundred', '一百', ''),
('Official', '6', 'Starter', 'two hundred', '二百、兩百', ''),
('Official', '6', 'Starter', 'three hundred', '三百', ''),
('Official', '6', 'Starter', 'four hundred', '四百', ''),
('Official', '6', 'Starter', 'five hundred', '五百', ''),
('Official', '6', 'Starter', 'six hundred', '六百', ''),
('Official', '6', 'Starter', 'seven hundred', '七百', ''),
('Official', '6', 'Starter', 'eight hundred', '八百', ''),
('Official', '6', 'Starter', 'nine hundred', '九百', ''),
('Official', '6', 'Starter', 'one thousand', '一千', ''),
('Official', '6', '1', 'eyes', '眼睛', ''),
('Official', '6', '1', 'ears', '耳朵', ''),
('Official', '6', '1', 'nose', '鼻子', ''),
('Official', '6', '1', 'mouth', '嘴、嘴巴', ''),
('Official', '6', '1', 'hands', '手', ''),
('Official', '6', '1', 'arms', '手臂', ''),
('Official', '6', '1', 'legs', '腿', ''),
('Official', '6', '1', 'foot', '腳', ''),
('Official', '6', '1', 'feet', '腳、腳(複數)', ''),
('Official', '6', '1', 'wrong', '不對的、錯誤的', ''),
('Official', '6', '1', 'hurt', '疼痛、痛', ''),
('Official', '6', '2', 'cold', '感冒、寒冷', ''),
('Official', '6', '2', 'fever', '發燒', ''),
('Official', '6', '2', 'runny nose', '流鼻涕', ''),
('Official', '6', '2', 'sore throat', '喉嚨痛', ''),
('Official', '6', '2', 'headache', '頭痛', ''),
('Official', '6', '2', 'toothache', '牙痛', ''),
('Official', '6', '2', 'stomachache', '胃痛', ''),
('Official', '6', '2', 'have', '有', ''),
('Official', '6', '2', 'has', '有', ''),
('Official', '6', '3', 'breakfast', '早餐', ''),
('Official', '6', '3', 'lunch', '午餐、中餐', ''),
('Official', '6', '3', 'dinner', '晚餐', ''),
('Official', '6', '3', 'bread', '麵包', ''),
('Official', '6', '3', 'chicken', '雞、雞肉', ''),
('Official', '6', '3', 'salad', '沙拉', ''),
('Official', '6', '3', 'soup', '湯', ''),
('Official', '6', '3', 'noodles', '麵條、麵', ''),
('Official', '6', '3', 'would like', '想要', ''),
('Official', '6', '3', 'please', '請', ''),
('Official', '6', '4', 'backpack', '背包', ''),
('Official', '6', '4', 'cap', '棒球帽', ''),
('Official', '6', '4', 'lunchbox', '午餐盒', ''),
('Official', '6', '4', 'umbrella', '雨傘', ''),
('Official', '6', '4', 'waterbottle', '水壺', ''),
('Official', '6', '4', 'workbook', '作業本', ''),
('Official', '6', '4', 'glasses', '眼鏡', ''),
('Official', '6', '4', 'shoes', '鞋、鞋子', ''),
('Official', '6', '4', 'whose', '誰的', ''),
('Official', '6', 'Festival', 'sachet', '香包', ''),
('Official', '6', 'Festival', 'zongzi', '粽子', ''),
('Official', '6', 'Festival', 'dragon boat race', '龍舟競賽', ''),
('Official', '6', 'Festival', 'stand an egg', '立蛋', ''),
('Official', '8', '1', 'at home', '在家', ''),
('Official', '8', '1', 'at school', '在學校', ''),
('Official', '8', '1', 'at the mall', '在購物中心', ''),
('Official', '8', '1', 'at the movie theater', '在電影院', ''),
('Official', '8', '1', 'at the restaurant', '在餐廳', ''),
('Official', '8', '1', 'at the zoo', '在動物園', ''),
('Official', '8', '1', 'was', '是、am的過去式、is的過去式', ''),
('Official', '8', '1', 'were', '是、are的過去式', ''),
('Official', '8', '1', 'yesterday', '昨天', ''),
('Official', '8', '2', 'cleaned my room', '打掃我的房間', ''),
('Official', '8', '2', 'listened to music', '聽音樂', ''),
('Official', '8', '2', 'played basketball', '打籃球', ''),
('Official', '8', '2', 'walked the dog', '遛狗', ''),
('Official', '8', '2', 'watched videos', '看影片', ''),
('Official', '8', '2', 'visited a friend', '拜訪朋友', ''),
('Official', '8', '2', 'did', 'do的過去式', ''),
('Official', '8', '2', 'last', '上一次、最後', ''),
('Official', '8', '2', 'night', '夜晚', ''),
('Official', '8', '3', 'coat', '外套、大衣', ''),
('Official', '8', '3', 'dress', '洋裝', ''),
('Official', '8', '3', 'hat', '帽子', ''),
('Official', '8', '3', 'jacket', '夾克', ''),
('Official', '8', '3', 'skirt', '裙子', ''),
('Official', '8', '3', 'T-shirt', 'T恤、短袖', ''),
('Official', '8', '3', 'jeans', '牛仔褲', ''),
('Official', '8', '3', 'pants', '褲子、長褲', ''),
('Official', '8', '3', 'shorts', '短褲', ''),
('Official', '8', '3', 'how much', '多少錢、多少', ''),
('Official', '8', '3', 'dollar', '元、美元', ''),
('Official', '8', '4', 'spring', '春天', ''),
('Official', '8', '4', 'summer', '夏天', ''),
('Official', '8', '4', 'fall', '秋天', ''),
('Official', '8', '4', 'winter', '冬天', ''),
('Official', '8', '4', 'dry', '乾燥的', ''),
('Official', '8', '4', 'wet', '潮濕的', ''),
('Official', '8', '4', 'foggy', '有霧的', ''),
('Official', '8', '4', 'snowy', '下雪的', ''),
('Official', '8', '4', 'favorite', '特別喜愛的、最愛的', ''),
('Official', '8', '4', 'season', '季節', ''),
('Official', '1', 'Starter', 'one', '一', ''),
('Official', '1', 'Starter', 'two', '二', ''),
('Official', '1', 'Starter', 'three', '三', ''),
('Official', '1', 'Starter', 'four', '四', ''),
('Official', '1', 'Starter', 'five', '五', ''),
('Official', '1', '1', 'I', '我', ''),
('Official', '1', '1', 'am', '是', ''),
('Official', '1', '1', 'is', '是', ''),
('Official', '1', '1', 'my', '我的', ''),
('Official', '1', '1', 'name', '名字', ''),
('Official', '1', '1', 'what', '什麼', ''),
('Official', '1', '1', 'your', '你的', ''),
('Official', '1', '2', 'six', '六', ''),
('Official', '1', '2', 'seven', '七', ''),
('Official', '1', '2', 'eight', '八', ''),
('Official', '1', '2', 'nine', '九', ''),
('Official', '1', '2', 'ten', '十', ''),
('Official', '1', '2', 'how old', '幾歲', ''),
('Official', '1', '2', 'are', '是', ''),
('Official', '1', '2', 'you', '你', ''),
('Official', '1', '2', 'year', '年、歲', ''),
('Official', '1', '3', 'book', '書', ''),
('Official', '1', '3', 'pen', '原子筆、筆', ''),
('Official', '1', '3', 'pencil', '鉛筆', ''),
('Official', '1', '3', 'eraser', '橡皮擦', ''),
('Official', '1', '3', 'ruler', '尺', ''),
('Official', '1', '3', 'marker', '彩色筆、馬克筆、麥克筆', ''),
('Official', '1', '3', 'this', '這個', ''),
('Official', '1', '3', 'that', '那個', ''),
('Official', '1', '3', 'it', '它、牠', ''),
('Official', '1', '3', 'a', '一個', ''),
('Official', '1', '4', 'blue', '藍色、藍色的', ''),
('Official', '1', '4', 'green', '綠色、綠色的', ''),
('Official', '1', '4', 'red', '紅色、紅色的', ''),
('Official', '1', '4', 'yellow', '黃色、黃色的', ''),
('Official', '1', '4', 'black', '黑色、黑色的', ''),
('Official', '1', '4', 'white', '白色、白色的', ''),
('Official', '1', '4', 'color', '顏色', ''),
('Official', '1', 'Festival', 'bat', '蝙蝠', ''),
('Official', '1', 'Festival', 'ghost', '鬼', ''),
('Official', '1', 'Festival', 'pumpkin', '南瓜', ''),
('Official', '1', 'Festival', 'spider', '蜘蛛', ''),
('Official', '1', 'Festival', 'witch', '女巫', ''),
('Official', '1', 'Festival', 'vampire', '吸血鬼', ''),
('Official', '3', 'Starter', 'sixteen', '十六', ''),
('Official', '3', 'Starter', 'seventeen', '十七', ''),
('Official', '3', 'Starter', 'eighteen', '十八', ''),
('Official', '3', 'Starter', 'nineteen', '十九', ''),
('Official', '3', 'Starter', 'twenty', '二十', ''),
('Official', '3', '1', 'sunny', '晴朗的', ''),
('Official', '3', '1', 'rainy', '下雨的', ''),
('Official', '3', '1', 'cloudy', '陰天的、多雲的', ''),
('Official', '3', '1', 'windy', '颳風的、刮風的', ''),
('Official', '3', '1', 'hot', '熱的、很熱的', ''),
('Official', '3', '1', 'warm', '溫暖的', ''),
('Official', '3', '1', 'cool', '涼爽的', ''),
('Official', '3', '1', 'cold', '寒冷的', ''),
('Official', '3', '1', 'weather', '天氣', ''),
('Official', '3', '2', 'angry', '生氣的', ''),
('Official', '3', '2', 'happy', '快樂的', ''),
('Official', '3', '2', 'sad', '傷心的', ''),
('Official', '3', '2', 'tired', '很累的', ''),
('Official', '3', '2', 'hungry', '肚子餓的', ''),
('Official', '3', '2', 'thirsty', '口渴的', ''),
('Official', '3', '2', 'full', '飽的', ''),
('Official', '3', '3', 'apple', '蘋果', ''),
('Official', '3', '3', 'banana', '香蕉', ''),
('Official', '3', '3', 'orange', '柳橙', ''),
('Official', '3', '3', 'watermelon', '西瓜', ''),
('Official', '3', '3', 'hot dog', '熱狗', ''),
('Official', '3', '3', 'hamburger', '漢堡', ''),
('Official', '3', '3', 'sandwich', '三明治', ''),
('Official', '3', '3', 'like', '喜歡', ''),
('Official', '3', '3', 'these', '這些', ''),
('Official', '3', '3', 'those', '那些', ''),
('Official', '3', '4', 'juice', '果汁', ''),
('Official', '3', '4', 'milk', '牛奶', ''),
('Official', '3', '4', 'water', '水', ''),
('Official', '3', '4', 'tea', '茶', ''),
('Official', '3', '4', 'cake', '蛋糕', ''),
('Official', '3', '4', 'pizza', '披薩', ''),
('Official', '3', '4', 'rice', '米飯、米、飯', ''),
('Official', '3', '4', 'ice cream', '冰淇淋', ''),
('Official', '3', '4', 'want', '想要', ''),
('Official', '3', '4', 'some', '一些', ''),
('Official', '3', 'Festival', 'eat', '吃', ''),
('Official', '3', 'Festival', 'moon cake', '月餅', ''),
('Official', '3', 'Festival', 'pomelo', '柚子', ''),
('Official', '3', 'Festival', 'Chang-O', '嫦娥', ''),
('Official', '3', 'Festival', 'Jade Rabbit', '玉兔', ''),
('Official', '5', 'Starter', 'ten', '十', ''),
('Official', '5', 'Starter', 'twenty', '二十', ''),
('Official', '5', 'Starter', 'thirty', '三十', ''),
('Official', '5', 'Starter', 'forty', '四十', ''),
('Official', '5', 'Starter', 'fifty', '五十', ''),
('Official', '5', 'Starter', 'sixty', '六十', ''),
('Official', '5', 'Starter', 'seventy', '七十', ''),
('Official', '5', 'Starter', 'eighty', '八十', ''),
('Official', '5', 'Starter', 'ninety', '九十', ''),
('Official', '5', 'Starter', 'one hundred', '一百', ''),
('Official', '5', '1', 'Sunday', '星期日、星期天', ''),
('Official', '5', '1', 'Monday', '星期一', ''),
('Official', '5', '1', 'Tuesday', '星期二', ''),
('Official', '5', '1', 'Wednesday', '星期三', ''),
('Official', '5', '1', 'Thursday', '星期四', ''),
('Official', '5', '1', 'Friday', '星期五', ''),
('Official', '5', '1', 'Saturday', '星期六', ''),
('Official', '5', '1', 'today', '今天、今日', ''),
('Official', '5', '2', 'art', '藝術', ''),
('Official', '5', '2', 'Chinese', '中文', ''),
('Official', '5', '2', 'English', '英語、英文', ''),
('Official', '5', '2', 'math', '數學', ''),
('Official', '5', '2', 'music', '音樂', ''),
('Official', '5', '2', 'PE', '體育', ''),
('Official', '5', '2', 'science', '自然', ''),
('Official', '5', '2', 'social studies', '社會', ''),
('Official', '5', '2', 'have', '有', ''),
('Official', '5', '2', 'class', '課', ''),
('Official', '5', '3', 'bank', '銀行', ''),
('Official', '5', '3', 'bookstore', '書店', ''),
('Official', '5', '3', 'hospital', '醫院', ''),
('Official', '5', '3', 'library', '圖書館', ''),
('Official', '5', '3', 'museum', '博物館', ''),
('Official', '5', '3', 'park', '公園', ''),
('Official', '5', '3', 'post office', '郵局', ''),
('Official', '5', '3', 'supermarket', '超級市場、超市', ''),
('Official', '5', '3', 'go', '去', ''),
('Official', '5', '3', 'road', '路', ''),
('Official', '5', '3', 'street', '街', ''),
('Official', '5', '4', 'elephant', '大象', ''),
('Official', '5', '4', 'horse', '馬', ''),
('Official', '5', '4', 'lion', '獅子', ''),
('Official', '5', '4', 'monkey', '猴子', ''),
('Official', '5', '4', 'tiger', '老虎', ''),
('Official', '5', '4', 'turtle', '烏龜', ''),
('Official', '5', '4', 'zebra', '斑馬', ''),
('Official', '5', '4', 'koala', '無尾熊', ''),
('Official', '5', '4', 'How many', '多少', ''),
('Official', '5', 'Festival', 'bell', '鈴鐺', ''),
('Official', '5', 'Festival', 'candy cane', '拐杖糖', ''),
('Official', '5', 'Festival', 'Christmas tree', '聖誕樹', ''),
('Official', '5', 'Festival', 'star', '星星', ''),
('Official', '5', 'Festival', 'stocking', '長襪', ''),
('Official', '5', 'Festival', 'Santa Claus', '耶誕老人、聖誕老人', ''),
('Official', '7', '1', 'Australia', '澳大利亞、澳洲', ''),
('Official', '7', '1', 'India', '印度', ''),
('Official', '7', '1', 'Japan', '日本', ''),
('Official', '7', '1', 'Singapore', '新加坡', ''),
('Official', '7', '1', 'Spain', '西班牙', ''),
('Official', '7', '1', 'Taiwan', '台灣、臺灣', ''),
('Official', '7', '1', 'the UK', '英國', ''),
('Official', '7', '1', 'the USA', '美國', ''),
('Official', '7', '1', 'from', '來自', ''),
('Official', '7', '2', 'by bike', '騎腳踏車', ''),
('Official', '7', '2', 'by bus', '搭公車', ''),
('Official', '7', '2', 'by car', '搭汽車、開車', ''),
('Official', '7', '2', 'by metro', '搭捷運', ''),
('Official', '7', '2', 'by scooter', '搭機車、騎機車', ''),
('Official', '7', '2', 'by taxi', '搭計程車', ''),
('Official', '7', '2', 'by train', '搭火車', ''),
('Official', '7', '2', 'on foot', '走路', ''),
('Official', '7', '2', 'school', '學校', ''),
('Official', '7', '3', 'go jogging', '慢跑', ''),
('Official', '7', '3', 'listen to music', '聽音樂', ''),
('Official', '7', '3', 'play baseball', '打棒球', ''),
('Official', '7', '3', 'play basketball', '打籃球', ''),
('Official', '7', '3', 'ride a bike', '騎腳踏車', ''),
('Official', '7', '3', 'study English', '研讀英語', ''),
('Official', '7', '3', 'surf the Internet', '上網', ''),
('Official', '7', '3', 'watch TV', '看電視', ''),
('Official', '7', '3', 'weekend', '週末', ''),
('Official', '7', '3', 'free time', '休閒時間', ''),
('Official', '7', '4', 'get up', '起床', ''),
('Official', '7', '4', 'go to school', '上學', ''),
('Official', '7', '4', 'have lunch', '吃午餐', ''),
('Official', '7', '4', 'go home', '回家', ''),
('Official', '7', '4', 'do my homework', '做我的功課', ''),
('Official', '7', '4', 'take a shower', '淋浴', ''),
('Official', '7', '4', 'go to bed', '上床睡覺', ''),
('Custom', 'Mario', '1', 'test', '測試', ''),
('Custom', 'Ibu', '2', 'demo', '示範', '');
